COMMENT = _{
    "#" ~ (!"\n" ~ ANY)*
}

WHITESPACE = _{
    " "
    | "\t"
    | "\r"
    | "\n"
    | COMMENT
}

Program = {
	SOI ~ Top_Level* ~ EOI
}

Identifier = @{
    ('a'..'z' | 'A'..'Z' | "_")
    ~ (ASCII_ALPHANUMERIC | "_")*
}

Use = {
    "import" ~
    "(" ~
    Identifier ~
    ")"
}

Top_Level = _{
	Use | Procedure
}

Procedure = {
	"proc" ~
    Identifier ~
    Procedure_Arguments? ~
    Procedure_Return_Kind? ~
    Body ~
    "<=proc"
}

String = { "str" }
Integer = { "int" }
Float = { "real" }
Boolean = { "bool" }
List = { "arr" }
Dictionary = { "dict" }

Procedure_Return_Kind = {
    ":" ~ Kind
}

Procedure_Arguments = {
    "("
    ~ (
    	Declaration_Data ~
        ("," ~ Declaration_Data)*
    )?
    ~ ")"
}

Declaration_Data = {
	Identifier ~ ":" ~ Kind
}

Kind = {
	Integer |
    String |
    Float |
    Boolean |
    List |
    Dictionary
}

Call = {
	Identifier ~
    "(" ~
    Call_Arguments? ~
    ")"
}

Call_Arguments = {
	Expression ~
    ("," ~ Expression)*
}

Expression = {
	Call |
    Add |
    Subtract |
    Multiply |
    Divide |
    Float_Literal |
    Integer_Literal |
    Boolean_Literal |
    String_Literal |
    And |
    Or |
    Not |
    Greater |
    Equal |
    Less |
    Greater_Equal |
    Less_Equal |
    Identifier
}

And = {
	"&&" ~
    Expression ~
    "->" ~
    Identifier
}

Or = {
	"||" ~
    Expression ~
    "->" ~
    Expression
}

Not = {
	"!" ~
    Expression
}

Greater = {
	">" ~
    Expression ~
    "->" ~
    Expression
}

Less = {
	"<" ~
    Expression ~
    "->" ~
    Expression
}

Greater_Equal = {
	">=" ~
    Expression ~
    "->" ~
    Expression
}

Less_Equal = {
	"<=" ~
    Expression ~
    "->" ~
    Expression
}

Equal = {
	"==" ~
    Expression ~
    "->" ~
    Expression
}

Add = {
	"+" ~
    Expression ~
    "->" ~
    Identifier
}

Subtract = {
	"-" ~
    Expression ~
    "->" ~
    Identifier
}

Multiply = {
	"*" ~
    Expression ~
    "->" ~
    Identifier
}

Divide = {
	"/" ~
    Expression ~
    "->" ~
    Identifier
}

Return = {
	">" ~ Expression
}

For = {
	"loop" ~
    Declaration_Data ~
    "->" ~
    Expression ~
    ".." ~
    Expression ~
    "+" ~
    Expression ~
    Body ~
    "<=loop"
}

If = {
	"if" ~
    Expression ~
    Body ~
    "<=if"
}

Else_If = {
	"elseif" ~
    Expression ~
    Body ~
    "<=elseif"
}

Else = {
	"else" ~
    Body ~
    "<=else"
}

Condition_Group = {
	If ~
	Else_If* ~
    Else?
}

While = {
	"while" ~
    Expression ~
    Body ~
    "<=while"
}

Declare = {
	"let" ~ Declaration_Data ~
    (
    	"->" ~
        Expression
    )?
}

Body = {
	"=>" ~
	(
    	Return |
        For |
        Condition_Group |
        While |
      	Declare |
      	Expression
    )*
}

Integer_Literal = @{
    ASCII_DIGIT+
}

Float_Literal = @{
    ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+
}

Boolean_Literal = _{
	True_Literal |
    False_Literal
}

True_Literal = { "true" }
False_Literal = { "false" }

String_Literal = @{
    ("\"" ~ Single_Line_String_Char* ~ "\"") |
    (
    	"`" ~ Multi_Line_String_Char* ~ "`"
	)
}

Single_Line_String_Char = @{
    Escape_Sequence
    | !("\"" | "\n" | "\r") ~ ANY
}

Multi_Line_String_Char = @{
    Escape_Sequence
    | !("`") ~ ANY
}

Escape_Sequence = _{
    "\\"
    ~ (
          "\""
        | "\\"
        | "`"
        | "n"
        | "r"
        | "t"
        | "0"
        | ("x" ~ ASCII_HEX_DIGIT ~ ASCII_HEX_DIGIT)
        | ("X" ~ ASCII_HEX_DIGIT ~ ASCII_HEX_DIGIT)
    )
}